development:
  clients:
    default:
      database: shopping_mg_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: shopping_mg_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true